### ISSUE TITLE
errors show up when trying to compile PBSPro

### ISSUE THREAD

**Issue by admerait** [PBSPro/pbspro#1577]
When trying to compile PBSPro I keep getting these errors. Can someone please assist with what could be causing this issue:

root@:/opt/pbspro-master# make

Generating ecl_resc_def_all.c from ../../../src/lib/Libattr/master_resc_def_all.xml
Traceback (most recent call last):
  File "../../../buildutils/attr_parser.py", line 78, in __iter__
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../../../buildutils/attr_parser.py", line 947, in <module>
    main(sys.argv[1:])
  File "../../../buildutils/attr_parser.py", line 928, in main
    resc_attr(m_file, s_file, e_file)
  File "../../../buildutils/attr_parser.py", line 529, in resc_attr
    for case in switch(mflg):
RuntimeError: generator raised StopIteration
Makefile:3688: recipe for target 'ecl_resc_def_all.c' failed
make[3]: *** [ecl_resc_def_all.c] Error 1
make[3]: Leaving directory '/opt/pbspro-master/src/lib/Libpbs'
Makefile:509: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/opt/pbspro-master/src/lib'
Makefile:511: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/opt/pbspro-master/src'
Makefile:547: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by mike0042** [comment]
Which OS and version are you using? What version(s) of Python are installed on the system?

**Comment by admerait** [comment]
Am using Ubuntu 18.04.3 LTS. The default Python version that is installed is 2.7.17.  Also, have python 3.7 installed and anaconda installed on the system as well.

**Comment by mike0042** [comment]
According to the Makefile, this is the command it attempted to run:

python /opt/pbspro-master/buildutils/attr_parser.py \
                -m /opt/pbspro-master/src/lib/Libattr/master_resc_def_all.xml \
                -s /dev/null -e ecl_resc_def_all.c -a resc

Do you get the same error if you run the command manually?

**Comment by admerait** [comment]
Yes, This is what I get when running it manually:
root@:/usr/local/bin# python /opt/pbspro-master/buildutils/attr_parser.py -m /opt/pbspro-master/src/lib/Libattr/master_resc_def_all.xml -s /dev/null -e ecl_resc_def_all.c -a resc
Traceback (most recent call last):
  File "/opt/pbspro-master/buildutils/attr_parser.py", line 947, in <module>
    main(sys.argv[1:])
  File "/opt/pbspro-master/buildutils/attr_parser.py", line 901, in main
    m_file = open(MASTER_FILE, encoding='utf-8')
TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by mike0042** [comment]
The "encoding" parameter is supported in Python3, but not Python2. Please try running the command again manually, but use python3 instead of python.

**Comment by admerait** [comment]
When running Python3 which is python version 3.7.6 it comes up with the same error:
root@: python3 /opt/pbspro-master/buildutils/attr_parser.py -m /opt/pbspro-master/src/lib/Libattr/master_resc_def_all.xml -s /dev/null -e ecl_resc_def_all.c -a resc
Traceback (most recent call last):
  File "/opt/pbspro-master/buildutils/attr_parser.py", line 78, in __iter__
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/pbspro-master/buildutils/attr_parser.py", line 947, in <module>
    main(sys.argv[1:])
  File "/opt/pbspro-master/buildutils/attr_parser.py", line 928, in main
    resc_attr(m_file, s_file, e_file)
  File "/opt/pbspro-master/buildutils/attr_parser.py", line 529, in resc_attr
    for case in switch(mflg):
RuntimeError: generator raised StopIteration

root@: python3
Python 3.7.6 (default, Dec 19 2019, 23:50:13)

**Comment by mike0042** [comment]
One of our internal systems runs Ubuntu 18.04.1 with Python 3.6.5, and the build works properly. It looks as though you've identified an incompatibility with Python 3.7.6. Thanks for filing the ticket. This will end up in our engineering backlog and be prioritized accordingly.

**Comment by ericpershey** [comment]
They changed Iterators in python 3.7: https://www.python.org/dev/peps/pep-0479/
I was going to create an issue on this but couldn't isolate the problem just yet.

**Comment by admerait** [comment]
@mike0042 I ran the configure with python 3.6 that we have installed.
PYTHON="/usr/bin/python3.6" ./configure --prefix=/opt/pbs
make

However, it comes up with a new error message. Seems to be related to python:
pbs_comm.c: In function ‘pbs_close_stdfiles’:
pbs_comm.c:438:3: warning: ignoring return value of ‘fopen’, declared with attribute warn_unused_result [-Wunused-result]
   fopen(NULL_DEVICE, "r");
   ^~~~~~~~~~~~~~~~~~~~~~~
pbs_comm.c:440:3: warning: ignoring return value of ‘fopen’, declared with attribute warn_unused_result [-Wunused-result]
   fopen(NULL_DEVICE, "w");
   ^~~~~~~~~~~~~~~~~~~~~~~
pbs_comm.c:441:3: warning: ignoring return value of ‘fopen’, declared with attribute warn_unused_result [-Wunused-result]
   fopen(NULL_DEVICE, "w");
   ^~~~~~~~~~~~~~~~~~~~~~~
pbs_comm.c: In function ‘lock_out’:
pbs_comm.c:251:5: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
     (void) ftruncate(fds, (off_t) 0);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pbs_comm.c:253:5: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
     (void) write(fds, buf, strlen(buf));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mv -f .deps/pbs_comm-pbs_comm.Tpo .deps/pbs_comm-pbs_comm.Po
/bin/bash ../../libtool  --tag=CC   --mode=link gcc  -g -O2   -o pbs_comm pbs_comm-pbs_comm.o ../../src/lib/Libtpp/libtpp.a ../../src/lib/Liblog/liblog.a ../../src/lib/Libutil/libutil.a ../../src/lib/Libpbs/.libs/libpbs.a -lpthread -lz  -ldl -lcrypt -lc -lc
libtool: link: gcc -g -O2 -o pbs_comm pbs_comm-pbs_comm.o  ../../src/lib/Libtpp/libtpp.a ../../src/lib/Liblog/liblog.a ../../src/lib/Libutil/libutil.a ../../src/lib/Libpbs/.libs/libpbs.a -lpthread -lz -ldl -lcrypt -lc
make[2]: Leaving directory '/opt/pbspro-master/src/server'
Making all in scheduler
make[2]: Entering directory '/opt/pbspro-master/src/scheduler'
Makefile:769: ../../src/lib/Libpython/.deps/libpbs_sched_a-shared_python_utils.Po: No such file or directory
make[2]: *** No rule to make target '../../src/lib/Libpython/.deps/libpbs_sched_a-shared_python_utils.Po'.  Stop.
make[2]: Leaving directory '/opt/pbspro-master/src/scheduler'
Makefile:511: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/opt/pbspro-master/src'
Makefile:547: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by mike0042** [comment]
Errors such as these are not uncommon when compiling PBS for the first time on a new platform. Each version of gcc issues more warnings for questionable practices, and we pass -Werror to the compiler which makes any warning an error. You have the option of removing the -Werror parameter passed to gcc. Once the latest Ubuntu release is officially supported, all warnings must be addressed. You're just a little ahead of the curve.

**Comment by admerait** [comment]
@mike0042 It looks like these errors need to be resolved, because after performing the make install the post installation instructions don't work due to missing files. Do you know what could be causing the errors below?:

root@:/opt/pbspro-master# make
Making all in scheduler
make[2]: Entering directory '/opt/pbspro-master/src/scheduler'
Makefile:769: ../../src/lib/Libpython/.deps/libpbs_sched_a-shared_python_utils.Po: No such file or directory
make[2]: *** No rule to make target '../../src/lib/Libpython/.deps/libpbs_sched_a-shared_python_utils.Po'. Stop.
make[2]: Leaving directory '/opt/pbspro-master/src/scheduler'
Makefile:511: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/opt/pbspro-master/src'
Makefile:547: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by mike0042** [comment]
Here's the output from a successful build under CentOS 7:

    make[2]: Entering directory `/home/mike/rpmbuild/BUILD/pbspro-19.3.5/build/src/scheduler'
    gcc -DHAVE_CONFIG_H -I. -I../../../src/scheduler -I../../src/include  -I../../../src/include -pthread -I/usr/include/python3.6m -I/usr/include/python3.6m    -g -O2 -pipe -Wall -Werror -MT libpbs_sched_a-shared_python_utils.o -MD -MP -MF .deps/libpbs_sched_a-shared_python_utils.Tpo -c -o libpbs_sched_a-shared_python_utils.o `test -f '../../src/lib/Libpython/shared_python_utils.c' || echo '../../../src/scheduler/'`../../src/lib/Libpython/shared_python_utils.c

The piece that stands out to me is the suffix on libpbs_sched_a-shared_python_utils.Tpo. The error message in your build uses a different suffix. Could it be that suffix has changed in newer versions of libtool? I would check the Libpython/.deps directory to see what files are present.

**Comment by admerait** [comment]
@mike0042 These are the files that are present in the Libpython/.deps directory. Are they the same as yours:
root@:/opt/pbspro-master/src/lib/Libpython/.deps# ls -l
total 204
-rw-r--r-- 1 root root 17267 Mar 13 17:36 libpbspython_a-common_python_utils.Po
-rw-r--r-- 1 root root 15893 Mar 13 17:36 libpbspython_a-pbs_ifl_wrap.Po
-rw-r--r-- 1 root root 19282 Mar 13 17:36 libpbspython_a-pbs_python_external.Po
-rw-r--r-- 1 root root 16584 Mar 13 17:36 libpbspython_a-shared_python_utils.Po
-rw-r--r-- 1 root root 22521 Mar 13 17:36 libpbspython_svr_a-module_pbs_v1.Po
-rw-r--r-- 1 root root 17080 Mar 13 17:36 libpbspython_svr_a-pbs_python_import_types.Po
-rw-r--r-- 1 root root 19313 Mar 13 17:36 libpbspython_svr_a-pbs_python_svr_external.Po
-rw-r--r-- 1 root root 23375 Mar 13 17:36 libpbspython_svr_a-pbs_python_svr_internal.Po
-rw-r--r-- 1 root root 19862 Mar 13 17:36 libpbspython_svr_a-pbs_python_svr_size_type.Po
-rw-r--r-- 1 root root 16588 Mar 13 17:36 libpbspython_svr_a-shared_python_utils.Po

**Comment by mike0042** [comment]
Mine looks similar.

    [mike@pbs-server SPECS]$ ls -l /home/mike/rpmbuild/BUILD/pbspro-19.3.5/build/src/lib/Libpython/.deps
    total 248
    -rw-r--r--. 1 mike mike 11672 Mar 18 16:44 libpbspython_a-common_python_utils.Po
    -rw-r--r--. 1 mike mike 15373 Mar 18 16:44 libpbspython_a-module_pbs_v1.Po
    -rw-r--r--. 1 mike mike 10311 Mar 18 16:44 libpbspython_a-pbs_ifl_wrap.Po
    -rw-r--r--. 1 mike mike 12074 Mar 18 16:44 libpbspython_a-pbs_python_external.Po
    -rw-r--r--. 1 mike mike 11463 Mar 18 16:44 libpbspython_a-pbs_python_import_types.Po
    -rw-r--r--. 1 mike mike 13793 Mar 18 16:44 libpbspython_a-pbs_python_svr_external.Po
    -rw-r--r--. 1 mike mike 16302 Mar 18 16:44 libpbspython_a-pbs_python_svr_internal.Po
    -rw-r--r--. 1 mike mike 12572 Mar 18 16:44 libpbspython_a-pbs_python_svr_size_type.Po
    -rw-r--r--. 1 mike mike 10929 Mar 18 16:44 libpbspython_a-shared_python_utils.Po
    -rw-r--r--. 1 mike mike 11676 Mar 18 16:44 libpbspython_svr_a-common_python_utils.Po
    -rw-r--r--. 1 mike mike 15377 Mar 18 16:44 libpbspython_svr_a-module_pbs_v1.Po
    -rw-r--r--. 1 mike mike 10315 Mar 18 16:44 libpbspython_svr_a-pbs_ifl_wrap.Po
    -rw-r--r--. 1 mike mike 12078 Mar 18 16:44 libpbspython_svr_a-pbs_python_external.Po
    -rw-r--r--. 1 mike mike 11467 Mar 18 16:44 libpbspython_svr_a-pbs_python_import_types.Po
    -rw-r--r--. 1 mike mike 13797 Mar 18 16:44 libpbspython_svr_a-pbs_python_svr_external.Po
    -rw-r--r--. 1 mike mike 16306 Mar 18 16:44 libpbspython_svr_a-pbs_python_svr_internal.Po
    -rw-r--r--. 1 mike mike 12576 Mar 18 16:44 libpbspython_svr_a-pbs_python_svr_size_type.Po
    -rw-r--r--. 1 mike mike 10933 Mar 18 16:44 libpbspython_svr_a-shared_python_utils.Po

I wonder if the content of your Makefiles are different.

    [mike@pbs-server src]$ grep -r libpbs_sched_a-shared_python_utils
    scheduler/Makefile:     libpbs_sched_a-shared_python_utils.$(OBJEXT) \
    scheduler/Makefile:include ./$(DEPDIR)/libpbs_sched_a-shared_python_utils.Po
    scheduler/Makefile:libpbs_sched_a-shared_python_utils.o: $(top_builddir)/src/lib/Libpython/shared_python_utils.c
    scheduler/Makefile:     $(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libpbs_sched_a_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libpbs_sched_a-shared_python_utils.o -MD -MP -MF $(DEPDIR)/libpbs_sched_a-shared_python_utils.Tpo -c -o libpbs_sched_a-shared_python_utils.o `test -f '$(top_builddir)/src/lib/Libpython/shared_python_utils.c' || echo '$(srcdir)/'`$(top_builddir)/src/lib/Libpython/shared_python_utils.c
    scheduler/Makefile:     $(AM_V_at)$(am__mv) $(DEPDIR)/libpbs_sched_a-shared_python_utils.Tpo $(DEPDIR)/libpbs_sched_a-shared_python_utils.Po
    scheduler/Makefile:#    $(AM_V_CC)source='$(top_builddir)/src/lib/Libpython/shared_python_utils.c' object='libpbs_sched_a-shared_python_utils.o' libtool=no \
    scheduler/Makefile:#    $(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libpbs_sched_a_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libpbs_sched_a-shared_python_utils.o `test -f '$(top_builddir)/src/lib/Libpython/shared_python_utils.c' || echo '$(srcdir)/'`$(top_builddir)/src/lib/Libpython/shared_python_utils.c
    scheduler/Makefile:libpbs_sched_a-shared_python_utils.obj: $(top_builddir)/src/lib/Libpython/shared_python_utils.c
    scheduler/Makefile:     $(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libpbs_sched_a_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libpbs_sched_a-shared_python_utils.obj -MD -MP -MF $(DEPDIR)/libpbs_sched_a-shared_python_utils.Tpo -c -o libpbs_sched_a-shared_python_utils.obj `if test -f '$(top_builddir)/src/lib/Libpython/shared_python_utils.c'; then $(CYGPATH_W) '$(top_builddir)/src/lib/Libpython/shared_python_utils.c'; else $(CYGPATH_W) '$(srcdir)/$(top_builddir)/src/lib/Libpython/shared_python_utils.c'; fi`
    scheduler/Makefile:     $(AM_V_at)$(am__mv) $(DEPDIR)/libpbs_sched_a-shared_python_utils.Tpo $(DEPDIR)/libpbs_sched_a-shared_python_utils.Po
    scheduler/Makefile:#    $(AM_V_CC)source='$(top_builddir)/src/lib/Libpython/shared_python_utils.c' object='libpbs_sched_a-shared_python_utils.obj' libtool=no \
    scheduler/Makefile:#    $(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libpbs_sched_a_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libpbs_sched_a-shared_python_utils.obj `if test -f '$(top_builddir)/src/lib/Libpython/shared_python_utils.c'; then $(CYGPATH_W) '$(top_builddir)/src/lib/Libpython/shared_python_utils.c'; else $(CYGPATH_W) '$(srcdir)/$(top_builddir)/src/lib/Libpython/shared_python_utils.c'; fi`
    Binary file scheduler/libpbs_sched.a matches
    scheduler/.deps/libpbs_sched_a-shared_python_utils.Po:libpbs_sched_a-shared_python_utils.o: \

**Comment by admerait** [comment]
@mike0042 Am wondering if it has to do with the way I handled warnings that I noticed from running the autogen.sh script?
I got a lot of the warnings dealing with "in a subdirectory but option 'subdir-objects' is disabled" so I had to insert "AUTOMAKE_OPTIONS = subdir-objects" to the makefiles in src/lib/Libpbs/Makefile.am | src/resmom/Makefile.am | src/scheduler/Makefile.am | src/tools/Makefile.am | 

Also, I received the non-POSIX variable name warnings below. I read that the warnings below can be ignored or did you do something differently?

root@:/opt/pbspro-master# ./autogen.sh
Generating configure script and Makefile templates.
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'buildutils'.
libtoolize: copying file 'buildutils/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:57: installing 'buildutils/compile'
configure.ac:56: installing 'buildutils/missing'
src/cmds/Makefile.am: installing 'buildutils/depcomp'
test/fw/Makefile.am:44: warning: wildcard $(srcdir: non-POSIX variable name
test/fw/Makefile.am:44: (probably a GNU make extension)
test/fw/Makefile.am:52: warning: wildcard $(builddir: non-POSIX variable name
test/fw/Makefile.am:52: (probably a GNU make extension)
test/fw/Makefile.am:56: warning: wildcard $(srcdir: non-POSIX variable name
test/fw/Makefile.am:56: (probably a GNU make extension)
test/fw/Makefile.am:60: warning: wildcard $(srcdir: non-POSIX variable name
test/fw/Makefile.am:60: (probably a GNU make extension)
test/fw/Makefile.am:64: warning: wildcard $(srcdir: non-POSIX variable name
test/fw/Makefile.am:64: (probably a GNU make extension)
test/fw/Makefile.am:68: warning: wildcard $(srcdir: non-POSIX variable name
test/fw/Makefile.am:68: (probably a GNU make extension)
automake: warning: wildcard $(srcdir: non-POSIX variable name
automake: (probably a GNU make extension)
test/fw/Makefile.am:44:   while processing 'dist_ptlpkg_bin_SCRIPTS'
automake: warning: wildcard $(srcdir: non-POSIX variable name
automake: (probably a GNU make extension)
test/fw/Makefile.am:68:   while processing 'dist_ptlpkg_pylib_jobs_PYTHON'
automake: warning: wildcard $(srcdir: non-POSIX variable name
automake: (probably a GNU make extension)
test/fw/Makefile.am:56:   while processing 'dist_ptlpkg_pylib_lib_PYTHON'
automake: warning: wildcard $(srcdir: non-POSIX variable name
automake: (probably a GNU make extension)
test/fw/Makefile.am:64:   while processing 'dist_ptlpkg_pylib_plugins_PYTHON'
automake: warning: wildcard $(builddir: non-POSIX variable name
automake: (probably a GNU make extension)
test/fw/Makefile.am:52:   while processing 'dist_ptlpkg_pylib_top_PYTHON'
automake: warning: wildcard $(srcdir: non-POSIX variable name
automake: (probably a GNU make extension)
test/fw/Makefile.am:60:   while processing 'dist_ptlpkg_pylib_utils_PYTHON'
test/tests/Makefile.am:39: warning: wildcard $(srcdir: non-POSIX variable name
test/tests/Makefile.am:39: (probably a GNU make extension)
test/tests/Makefile.am:42: warning: wildcard $(srcdir: non-POSIX variable name
test/tests/Makefile.am:42: (probably a GNU make extension)
test/tests/Makefile.am:45: warning: wildcard $(srcdir: non-POSIX variable name
test/tests/Makefile.am:45: (probably a GNU make extension)
test/tests/Makefile.am:48: warning: wildcard $(srcdir: non-POSIX variable name
test/tests/Makefile.am:48: (probably a GNU make extension)
test/tests/Makefile.am:51: warning: wildcard $(srcdir: non-POSIX variable name
test/tests/Makefile.am:51: (probably a GNU make extension)
test/tests/Makefile.am:54: warning: wildcard $(srcdir: non-POSIX variable name
test/tests/Makefile.am:54: (probably a GNU make extension)
test/tests/Makefile.am:57: warning: wildcard $(srcdir: non-POSIX variable name
test/tests/Makefile.am:57: (probably a GNU make extension)
test/tests/Makefile.am:60: warning: wildcard $(srcdir: non-POSIX variable name
test/tests/Makefile.am:60: (probably a GNU make extension)
automake: warning: wildcard $(srcdir: non-POSIX variable name
automake: (probably a GNU make extension)
test/tests/Makefile.am:39:   while processing 'dist_ptl_tests_PYTHON'
automake: warning: wildcard $(srcdir: non-POSIX variable name
automake: (probably a GNU make extension)
test/tests/Makefile.am:42:   while processing 'dist_ptl_testfunctional_DATA'
automake: warning: wildcard $(srcdir: non-POSIX variable name
automake: (probably a GNU make extension)
test/tests/Makefile.am:45:   while processing 'dist_ptl_testinterfaces_DATA'
automake: warning: wildcard $(srcdir: non-POSIX variable name
automake: (probably a GNU make extension)
test/tests/Makefile.am:48:   while processing 'dist_ptl_testperformance_DATA'
automake: warning: wildcard $(srcdir: non-POSIX variable name
automake: (probably a GNU make extension)
test/tests/Makefile.am:51:   while processing 'dist_ptl_testresilience_DATA'
automake: warning: wildcard $(srcdir: non-POSIX variable name
automake: (probably a GNU make extension)
test/tests/Makefile.am:54:   while processing 'dist_ptl_testsecurity_DATA'
automake: warning: wildcard $(srcdir: non-POSIX variable name
automake: (probably a GNU make extension)
test/tests/Makefile.am:57:   while processing 'dist_ptl_testselftest_DATA'
automake: warning: wildcard $(srcdir: non-POSIX variable name
automake: (probably a GNU make extension)
test/tests/Makefile.am:60:   while processing 'dist_ptl_testupgrades_DATA'
root@:/opt/pbspro-master#


src/lib/Libpbs/Makefile.am:57: warning: source file '../Libattr/attr_fn_arst.c' is in a subdirectory,
src/lib/Libpbs/Makefile.am:57: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
src/lib/Libpbs/Makefile.am:57: warning: source file '../Libattr/attr_fn_b.c' is in a subdirectory,
src/lib/Libpbs/Makefile.am:57: but option 'subdir-objects' is disabled

**Comment by mike0042** [comment]
We use wildcards in the tests directory so that when someone adds a new file it automatically gets packaged without also having to update the Makefile.am. That is a GNU extension, and automake complains about it, but it makes it easier for the developer and testers. You may ignore thos warnings.

The warnings about subdir-objects may also be ignored. The layout of the library code hasn't changed in a very long time and more recent versions of automake complain. That wasn't always the case.

**Comment by Gilbert-serenasoft** [comment]
I get the same error on code pulled today (4/29). Running OpenSuse Tumbleweed and Anaconda with Python 3.7.6. This was on  a new computer. I did not have this problem last year with earlier versions of OpenSuse Tumbleweed and python. The old computer and old installation of pbspro still run but that code is using libhwloc.so.5 and it complains about libhwloc.so.15 on the new computer (I tried just moving the old binary).
